name: Rubocop

on:
  push:

jobs:
  build:
    name: CI Rubocop
    runs-on: ubuntu-latest
    env:
      BUNDLE_GITHUB__COM: ${{secrets.BUNDLE_GITHUB__COM}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Rubocop report
        run: bundle exec rubocop --format github
